### ISSUE TITLE
PlotDisplay not showing up

### ISSUE THREAD

**Issue by K4dUM** [CNS-OIST/STEPS#35]
Hello,
I wanted to try out the STEPS live visualizations, but I have run into an issue with the PlotDisplay window. Whenever I start the API_2 example script ip3r_sim.py, all the SimDisplay windows show up and work just fine. But a window for plots has never popped up and I don't see any errors for that. Would you maybe share your configuration that got it running?

I am using Ubuntu 22.04.3. I tried to follow the instructions from the Dockerfile in the STEPS_Docker repo and installed the STEPS 5.0.0 beta. All the other example scripts from API_2 work fine. I then used pip to install PyQt5 5.15.10 and pyqtgraph 0.13.3.
When I first ran the script ip3r_sim.py, I only got the SimControl and some empty windows and this console output:
```
Model checking:
No errors were found
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[2024-01-10 13:41:05,373][INFO][/var/src/STEPS/src/steps/tetexact/tetexact.cpp:123][virtual void steps::tetexact::Tetexact::checkpoint(const string&)]: Checkpoint to  _temp_sim0.cp ... 
[2024-01-10 13:41:05,377][INFO][/var/src/STEPS/src/steps/tetexact/tetexact.cpp:215][virtual void steps::tetexact::Tetexact::checkpoint(const string&)]: complete.
 
/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py:244: RuntimeWarning: 
Traceback (most recent call last):
  File "/home/maxim/STEPS_Example/python_scripts/API_2/visual/ip3r_sim.py", line 160, in <module>
    sc.run()
  File "/opt/conda/lib/python3.9/site-packages/steps/API_2/visual.py", line 152, in run
    self._window = self._app.exec_()
  File "/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 223, in paintGL
    self.drawItemTree(useItemNames=useItemNames)
  File "/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 255, in drawItemTree
    self.drawItemTree(i, useItemNames=useItemNames)
  File "/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 244, in drawItemTree
    debug.printExc()
  --- exception caught here ---
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 241, in drawItemTree
    i.paint()
  File "/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/items/GLMeshItem.py", line 177, in paint
    glVertexPointerf(verts)
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/wrapper.py", line 626, in wrapperCall
    storeValues(
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/arrays/arrayhelpers.py", line 156, in __call__
    contextdata.setValue( self.constant, pyArgs[self.pointerIndex] )
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/contextdata.py", line 40, in getContext
    raise error.Error(
OpenGL.error.Error: Attempt to retrieve context when no valid context
  debug.printExc()
Error while drawing item <steps.API_2.visual._GenericSurfElem object at 0x7f75e4b82b80>.
/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py:244: RuntimeWarning: 
Traceback (most recent call last):
  File "/home/maxim/STEPS_Example/python_scripts/API_2/visual/ip3r_sim.py", line 160, in <module>
    sc.run()
  File "/opt/conda/lib/python3.9/site-packages/steps/API_2/visual.py", line 152, in run
    self._window = self._app.exec_()
  File "/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 223, in paintGL
    self.drawItemTree(useItemNames=useItemNames)
  File "/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 255, in drawItemTree
    self.drawItemTree(i, useItemNames=useItemNames)
  File "/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 244, in drawItemTree
    debug.printExc()
  --- exception caught here ---
  File "/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 241, in drawItemTree
    i.paint()
  File "/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/items/GLScatterPlotItem.py", line 132, in paint
    glVertexPointerf(pos)
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/wrapper.py", line 626, in wrapperCall
    storeValues(
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/arrays/arrayhelpers.py", line 156, in __call__
    contextdata.setValue( self.constant, pyArgs[self.pointerIndex] )
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/contextdata.py", line 40, in getContext
    raise error.Error(
OpenGL.error.Error: Attempt to retrieve context when no valid context
  debug.printExc()
Error while drawing item <steps.API_2.visual._GenericTetScatterElem object at 0x7f75e4b99dc0>.
/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py:244: RuntimeWarning: 
Traceback (most recent call last):
  File "/home/maxim/STEPS_Example/python_scripts/API_2/visual/ip3r_sim.py", line 160, in <module>
    sc.run()
  File "/opt/conda/lib/python3.9/site-packages/steps/API_2/visual.py", line 152, in run
    self._window = self._app.exec_()
  File "/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 223, in paintGL
    self.drawItemTree(useItemNames=useItemNames)
  File "/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 255, in drawItemTree
    self.drawItemTree(i, useItemNames=useItemNames)
  File "/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 244, in drawItemTree
    debug.printExc()
  --- exception caught here ---
  File "/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 241, in drawItemTree
    i.paint()
  File "/home/maxim/.local/lib/python3.9/site-packages/pyqtgraph/opengl/items/GLMeshItem.py", line 177, in paint
    glVertexPointerf(verts)
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/wrapper.py", line 626, in wrapperCall
    storeValues(
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/arrays/arrayhelpers.py", line 156, in __call__
    contextdata.setValue( self.constant, pyArgs[self.pointerIndex] )
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/contextdata.py", line 40, in getContext
    raise error.Error(
OpenGL.error.Error: Attempt to retrieve context when no valid context
  debug.printExc()

```
Followed by a lot of errors like these
```
Error while drawing item <steps.API_2.visual._GenericSurfElem object at 0x7f75e4b99f70>.
Error while drawing item <steps.API_2.visual._GenericTetScatterElem object at 0x7f75c370e1f0>.
```
After I did `export QT_QPA_PLATFORM=wayland` the SimDisplay worked without problems and I could run the simulation with the SimControl. I still got these warnings and no plots:

```
Model checking:
No errors were found
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
[2024-01-10 13:45:13,866][INFO][/var/src/STEPS/src/steps/tetexact/tetexact.cpp:123][virtual void steps::tetexact::Tetexact::checkpoint(const string&)]: Checkpoint to  _temp_sim0.cp ... 
[2024-01-10 13:45:13,871][INFO][/var/src/STEPS/src/steps/tetexact/tetexact.cpp:215][virtual void steps::tetexact::Tetexact::checkpoint(const string&)]: complete.
```

I tried to find a solution, so I followed the instructions from [here](https://stackoverflow.com/a/69863722) to change my windowing system from wayland to Xorg. The warnings disappeared and the simulation with the 3D models works nicely, but there is no trace of the PlotDisplay window.

So I don't know what is causing this problem and how to properly set up my environment, and I would be glad if you could help me out.

**Comment by jlallouette** [comment]
Hello @K4dUM,

Thank you for reporting this issue. It should be fixed after applying this patch [plotdisplay_fix.txt](https://github.com/CNS-OIST/STEPS/files/13926464/plotdisplay_fix.txt) with:
```
cd /opt/conda/lib/python3.9/site-packages/steps
patch -p0 < /path/to/plotdisplay_fix.txt
```
The issue seems to have been caused by the switch from `pyqtgraph.GraphicsWindow` (which is now deprecated) to `pyqtgraph.GraphicsLayoutWidget`.
The fix will be included in the next STEPS release.

**Comment by K4dUM** [comment]
Thank you @jlallouette , works fine now.
