### ISSUE TITLE
incompatibility with Anaconda

### ISSUE THREAD

**Issue by WeiliangChenOIST** [CNS-OIST/STEPS#6]
@FrancescoCasalegno @adevress 

One user has reported an issue importing STEPS with Ubuntu 16.04 and Anaconda, as follows:

```
urakubo-h@knv00:~/SOFTWARES/STEPS-master/build$ python
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
import steps
Unable to import STEPS with NumPy support, try to import without NumPy...
Unable to import STEPS.
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/home/urakubo-h/anaconda/lib/python2.7/site-packages/steps/__init__.py", line 46, in <module>
   _steps_swig.init()
NameError: name '_steps_swig' is not defined
```
The installation log seems fine.

[steps_install2.txt](https://github.com/CNS-OIST/STEPS/files/981359/steps_install2.txt)

I've reproduced the issue with this docker image [anaconda_steps](https://hub.docker.com/r/wchenoist/anaconda_steps/).

Interestingly, replacing Anaconda with Miniconda resolves the issue, as shown in this docker image [miniconda_steps](https://hub.docker.com/r/wchenoist/miniconda_steps/), so I assume the issue comes from Anaconda. Any idea what could cause this issue?

**Comment by WeiliangChenOIST** [comment]
`conda install libgcc` resolves the issue in anaconda_steps docker. But the user still has problem.

Here is the ldd info

```
urakubo-h@knv00:~$ ldd /home/urakubo-h/anaconda/lib/python2.7/site-packages/steps/_steps_swig_numpy.so 
	linux-vdso.so.1 =>  (0x00007ffc2ebf1000)
	libpython2.7.so.1.0 => /home/urakubo-h/anaconda/lib/libpython2.7.so.1.0 (0x00007ff5a5456000)
	libmpi.so.12 => /usr/lib/libmpi.so.12 (0x00007ff5a5149000)
	libmpi_cxx.so.1 => /usr/lib/libmpi_cxx.so.1 (0x00007ff5a4f2d000)
	liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007ff5a474a000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007ff5a44e9000)
	libstdc++.so.6 => /home/urakubo-h/anaconda/lib/libstdc++.so.6 (0x00007ff5a412c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff5a3e23000)
	libgcc_s.so.1 => /home/urakubo-h/anaconda/lib/libgcc_s.so.1 (0x00007ff5a3c0c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff5a3842000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff5a3625000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff5a3421000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007ff5a321d000)
	libibverbs.so.1 => /usr/lib/libibverbs.so.1 (0x00007ff5a300e000)
	libopen-rte.so.12 => /usr/lib/libopen-rte.so.12 (0x00007ff5a2d94000)
	libopen-pal.so.13 => /usr/lib/libopen-pal.so.13 (0x00007ff5a2af6000)
	libopenblas.so.0 => /home/urakubo-h/anaconda/lib/libopenblas.so.0 (0x00007ff5a1ab3000)
	libgfortran.so.3 => /home/urakubo-h/anaconda/lib/libgfortran.so.3 (0x00007ff5a17aa000)
	/lib64/ld-linux-x86-64.so.2 (0x0000559440f08000)
	libhwloc.so.5 => /usr/lib/x86_64-linux-gnu/libhwloc.so.5 (0x00007ff5a156f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff5a1367000)
	libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007ff5a115b000)
	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007ff5a0f51000)

```

**Comment by WeiliangChenOIST** [comment]
Solved. 
[steps_install7.txt](https://github.com/CNS-OIST/STEPS/files/982026/steps_install7.txt)

OpenMPI still has problem initializing, work on it separately.
